version: "2"

services:
  app:
    restart: always
    build: "."
    ports:
      - 127.0.0.1:80:3000
    env_file: .env
    environment:
      - REDIS_HOST=redis
    links:
      - redis
  redis:
    restart: always
    image: redis
